/* Catálogo de la app: músculos, ejercicios posibles con el equipo de la casa
   y los esquemas de series. Los textos van en la voz de Brooks Kubik. */

/* Horas de descanso tras trabajar un músculo como principal. Si el ejercicio
   solo lo toca de rebote (secundario), basta un tercio. */
const MUSCULOS = [
  { id: 'cuadriceps',   nombre: 'Cuádriceps',          corto: 'Cuádriceps',  zona: 'inf',  descanso: 72,
    porque: 'Músculo grande, y la sentadilla pesada también cansa el sistema nervioso. 72 horas completas.' },
  { id: 'gluteos',      nombre: 'Glúteos e isquios',   corto: 'Glúteos',     zona: 'inf',  descanso: 72,
    porque: 'Es el motor del peso muerto. Si no descansa, lo notas en la próxima sentadilla.' },
  { id: 'lumbares',     nombre: 'Espalda baja',        corto: 'Lumbares',    zona: 'inf',  descanso: 72,
    porque: 'Participa en casi todo lo que haces de pie. Es la que más tarda en recuperarse.' },
  { id: 'pecho',        nombre: 'Pecho',               corto: 'Pecho',       zona: 'sup',  descanso: 72,
    porque: 'Músculo grande. Con presses pesados, 72 horas.' },
  { id: 'espalda',      nombre: 'Espalda (dorsales)',  corto: 'Dorsales',    zona: 'sup',  descanso: 72,
    porque: 'Músculo grande. Con dominadas y remos pesados, 72 horas.' },
  { id: 'hombros',      nombre: 'Hombros',             corto: 'Hombros',     zona: 'sup',  descanso: 72,
    porque: 'Trabajan en todo press, también en el de banca. Mejor darles el descanso completo.' },
  { id: 'trapecios',    nombre: 'Trapecios',           corto: 'Trapecios',   zona: 'sup',  descanso: 60,
    porque: 'Aguantan mucho trabajo; con 60 horas llegan bien.' },
  { id: 'triceps',      nombre: 'Tríceps',             corto: 'Tríceps',     zona: 'sup',  descanso: 60,
    porque: 'Más chico que el pecho, pero carga con todos los presses. 60 horas.' },
  { id: 'biceps',       nombre: 'Bíceps',              corto: 'Bíceps',      zona: 'sup',  descanso: 48,
    porque: 'Músculo chico: se recupera en unas 48 horas. Por eso aguanta dominadas y curls dos o tres veces por semana.' },
  { id: 'agarre',       nombre: 'Antebrazos y agarre', corto: 'Agarre',      zona: 'comp', descanso: 48,
    porque: 'Los antebrazos se recuperan rápido. Kubik entrenaba el agarre en cada sesión.' },
  { id: 'core',         nombre: 'Abdomen',             corto: 'Abdomen',     zona: 'comp', descanso: 48,
    porque: 'Se recupera rápido. En el programa de Kubik el tronco se trabaja en todas las sesiones.' },
  { id: 'cuello',       nombre: 'Cuello',              corto: 'Cuello',      zona: 'comp', descanso: 48,
    porque: 'Músculo chico que aguanta bien el trabajo. Kubik lo entrenaba como los luchadores de antes: con arnés y varias veces por semana.' },
  { id: 'pantorrillas', nombre: 'Pantorrillas',        corto: 'Pantorrillas', zona: 'comp', descanso: 48,
    porque: 'Aguantan mucho: caminas con ellas todo el día.' },
];

const ZONAS = {
  inf:  'Piernas, cadera y espalda baja',
  sup:  'Torso y brazos',
  comp: 'Agarre, abdomen, cuello y pantorrillas',
};

/* Esquemas de series. No hay que anotar kilos: el texto dice cómo medir el
   esfuerzo y cuándo subir. */
const ESQUEMAS = {
  cinco:     { nombre: '5 × 5',           texto: 'Dos series subiendo el peso y tres series de 5 con el mismo peso. Si salen las 15 repeticiones, la próxima vez ponle más.' },
  simples:   { nombre: 'Simples',         texto: 'Repeticiones sueltas subiendo a saltos, 4 o 5 en total, hasta una última que casi no sale. Descansa 2 a 3 minutos entre cada una. Si todavía no llevas unos meses de 5 × 5, hoy haz 5 × 5.' },
  escalera:  { nombre: '5-4-3-2-1',       texto: 'Dos series de calentamiento y luego 5, 4, 3, 2 y 1 repeticiones, subiendo un poco el peso en cada una.' },
  muerte:    { nombre: 'Serie a muerte',  texto: 'Calienta y haz UNA serie de 20 repeticiones con un peso que normalmente sacarías 10 veces. Cuando se ponga feo, respira hondo entre repeticiones. No se para.' },
  parcial:   { nombre: '3 × 3 pesado',    texto: 'Tres series de 3 subiendo el peso. El recorrido es corto: carga más que en el ejercicio completo.' },
  maxreps:   { nombre: 'Al máximo',       texto: '3 a 5 series de tantas repeticiones como salgan con buena técnica. Cuando pases de 10, agrega peso: en dominadas, fondos, flexiones y sentadillas, ponte el chaleco de 10 kg.' },
  ocho:      { nombre: '3 × 8',           texto: 'Tres series de 8 a 10, estrictas, con un peso que no te deje hacer más.' },
  fijo:      { nombre: 'Peso fijo',       texto: 'El peso no cambia, así que la progresión eres tú: 3 series de tantas como salgan, más que la vez pasada o con menos descanso.' },
  reloj:     { nombre: 'Simples en 10 min', texto: 'Tantas repeticiones sueltas como puedas en 10 minutos, descansando lo justo. Técnica limpia en cada una.' },
  distancia: { nombre: 'Distancia',       texto: '3 a 5 viajes de 30 a 50 metros. Descansa solo lo necesario.' },
  lado:      { nombre: 'Por lado',        texto: '3 viajes de 30 metros con cada mano.' },
  tiempo:    { nombre: 'Contra el reloj', texto: '3 intentos, lo más largos posible. Intenta ganarle al anterior.' },
  abdominal: { nombre: '15 a 25',         texto: '1 o 2 series de 15 a 25 repeticiones.' },
  turca:     { nombre: '3 por lado',      texto: '3 por lado, lento y controlado.' },
  calentar:  { nombre: 'Calentamiento',   texto: '2 a 5 minutos, suave.' },
  burpees:   { nombre: 'Para terminar',   texto: '5 minutos: tantos burpees como puedas, descansando lo justo. O 5 rondas de 10 contra el reloj.' },
  cuello:    { nombre: '3 × 15-20',       texto: 'Tres series de 15 a 20, lentas y sin tirones: el cuello no se entrena a golpes. Cuando salgan 20 limpias en las tres, agrega un disco chico.' },
  complemento: { nombre: '2 × 10-12',     texto: 'Dos series de 10 a 12. Es complemento: no le robes energía a lo importante.' },
};

/* Cada ejercicio: músculos principales (p) y secundarios (s), patrón de
   movimiento (para armar la rutina), esquemas que se van turnando y equipo.
   kubik: false = no entra en las rutinas sugeridas, pero se puede registrar.
   planB: true = entra solo si la opción de peso libre está vetada.
   grupo: sentadilla y peso muerto nunca van en la misma sesión (GRUPOS_EXCLUYENTES). */
const GRUPOS_EXCLUYENTES = { sentadilla: 'Sentadilla', peso_muerto: 'Peso muerto' };
const CATEGORIAS = [
  { id: 'piernas',  nombre: 'Piernas' },
  { id: 'bisagra',  nombre: 'Peso muerto y espalda baja' },
  { id: 'empujes',  nombre: 'Empujes' },
  { id: 'tirones',  nombre: 'Tirones' },
  { id: 'tronco80', nombre: 'Tronco de 80 kg' },
  { id: 'agarre',   nombre: 'Agarre y acarreos' },
  { id: 'brazos',   nombre: 'Brazos' },
  { id: 'abdomen',  nombre: 'Abdomen' },
  { id: 'cuello',   nombre: 'Cuello' },
  { id: 'poleas',   nombre: 'Poleas (complementos)' },
  { id: 'tobillera', nombre: 'Tobillera (polea baja)' },
  { id: 'banda',    nombre: 'Banda de resistencia' },
  { id: 'otros',    nombre: 'Calentamiento y acondicionamiento' },
  { id: 'crossfit', nombre: 'CrossFit' },
];

const EJERCICIOS = [
  /* ---------- piernas ---------- */
  { id: 'sent_abajo', grupo: 'sentadilla', base: true, cat: 'piernas', pat: 'sentadilla', equipo: 'Jaula + barra',
    nombre: 'Sentadilla desde abajo',
    p: ['cuadriceps', 'gluteos'], s: ['lumbares', 'core'], esq: ['simples', 'cinco'],
    tip: 'Pon los seguros a la altura del fondo de la sentadilla y parte desde ahí, sin rebote. Es la forma más dura de hacer sentadilla, y por eso sirve.' },
  { id: 'sent', grupo: 'sentadilla', base: true, cat: 'piernas', pat: 'sentadilla', equipo: 'Jaula + barra',
    nombre: 'Sentadilla trasera',
    p: ['cuadriceps', 'gluteos'], s: ['lumbares', 'core'], esq: ['cinco', 'muerte', 'escalera'],
    tip: 'Baja hasta la paralela o más. Nada de vendas ni trajes: el trabajo lo hacen tus piernas. Con 140 kg en total, si te queda corto, la respuesta es la serie a muerte, no más discos.' },
  { id: 'sent_frontal', grupo: 'sentadilla', cat: 'piernas', pat: 'sentadilla', equipo: 'Jaula + barra',
    nombre: 'Sentadilla frontal',
    p: ['cuadriceps'], s: ['gluteos', 'core', 'lumbares'], esq: ['cinco', 'simples'],
    tip: 'La barra sobre los hombros, codos arriba. Castiga los muslos y te enseña a mantener el torso derecho.' },
  { id: 'cuarto_sent', grupo: 'sentadilla', cat: 'piernas', pat: 'parcial', equipo: 'Jaula + barra',
    nombre: '¼ de sentadilla en la jaula',
    p: ['cuadriceps'], s: ['gluteos', 'lumbares', 'trapecios'], esq: ['parcial'],
    tip: 'Recorrido corto y peso enorme: seguros un poco sobre la mitad del recorrido. Fortalece tendones y te acostumbra a sentir peso de verdad.' },
  { id: 'zancadas_maletas', cat: 'piernas', pat: 'sentadilla', equipo: 'Maletas', kubik: false,
    nombre: 'Zancadas con maletas',
    p: ['cuadriceps', 'gluteos'], s: ['agarre', 'core'], esq: ['fijo'],
    tip: 'Paso largo, la rodilla de atrás casi al suelo. No es de Kubik, pero no le hace mal a nadie.' },
  { id: 'talones', cat: 'piernas', pat: 'pantorrilla', equipo: 'Jaula + barra',
    nombre: 'Elevación de talones con barra',
    p: ['pantorrillas'], s: [], esq: ['maxreps'],
    tip: 'Barra en la espalda dentro de la jaula y las puntas sobre un disco. Sube, sostén arriba y baja lento.' },

  /* ---------- peso muerto y espalda baja ---------- */
  { id: 'pm_trap', grupo: 'peso_muerto', base: true, cat: 'bisagra', pat: 'bisagra', equipo: 'Barra hexagonal',
    nombre: 'Peso muerto con barra hexagonal',
    p: ['gluteos', 'cuadriceps', 'lumbares'], s: ['trapecios', 'agarre', 'espalda'], esq: ['cinco', 'muerte', 'simples'],
    tip: 'La barra hexagonal cuida la espalda y deja cargar fuerte. Si 140 kg ya te quedan cortos, no te quejes: haz la serie a muerte.' },
  { id: 'pm', grupo: 'peso_muerto', base: true, cat: 'bisagra', pat: 'bisagra', equipo: 'Barra olímpica',
    nombre: 'Peso muerto convencional',
    p: ['gluteos', 'lumbares'], s: ['cuadriceps', 'trapecios', 'agarre', 'espalda'], esq: ['cinco', 'simples', 'escalera'],
    tip: 'Espalda plana, barra pegada a las piernas y tira como si quisieras arrancar el piso.' },
  { id: 'pm_parcial', grupo: 'peso_muerto', cat: 'bisagra', pat: 'parcial', equipo: 'Jaula + barra',
    nombre: 'Peso muerto parcial desde la rodilla',
    p: ['lumbares', 'gluteos', 'trapecios'], s: ['agarre', 'espalda'], esq: ['parcial'],
    tip: 'Seguros a la altura de la rodilla. Aquí se mueve más que en el peso muerto completo; las manos van a pedir piedad antes que la espalda.' },
  { id: 'pm_maletas', grupo: 'peso_muerto', cat: 'bisagra', pat: 'bisagra', equipo: 'Maletas',
    nombre: 'Peso muerto con maletas',
    p: ['gluteos', 'cuadriceps', 'lumbares'], s: ['trapecios', 'agarre'], esq: ['fijo', 'muerte'],
    tip: 'Una maleta a cada lado, como el peso muerto con mancuernas del programa de Kubik. El peso es fijo: la progresión son las repeticiones.' },
  { id: 'pm_rumano', grupo: 'peso_muerto', cat: 'bisagra', pat: 'bisagra', equipo: 'Barra olímpica',
    nombre: 'Peso muerto rumano',
    p: ['gluteos', 'lumbares'], s: ['agarre', 'trapecios'], esq: ['cinco'],
    tip: 'Rodillas apenas dobladas y la cadera atrás. Baja hasta que los isquios reclamen.' },
  { id: 'buenos_dias', cat: 'bisagra', pat: 'bisagra', equipo: 'Jaula + barra',
    nombre: 'Buenos días con barra',
    p: ['gluteos', 'lumbares'], s: ['core'], esq: ['cinco'],
    tip: 'Liviano al principio. Construye la espalda baja que protege todo lo demás.' },

  /* ---------- empujes ---------- */
  { id: 'press_pie', base: true, cat: 'empujes', pat: 'empuje_v', equipo: 'Jaula + barra',
    nombre: 'Press militar de pie',
    p: ['hombros', 'triceps'], s: ['trapecios', 'core'], esq: ['cinco', 'simples', 'escalera'],
    tip: 'De pie, siempre. Sentado es para quien quiere seguir con la espalda baja débil.' },
  { id: 'press_frente', cat: 'empujes', pat: 'empuje_v', equipo: 'Jaula + barra',
    nombre: 'Press de pie desde la frente',
    p: ['hombros', 'triceps'], s: ['trapecios', 'core'], esq: ['simples', 'parcial'],
    tip: 'Seguros a la altura de la frente y empuja hasta estirar los brazos. Recorrido corto, carga pesada.' },
  { id: 'cargada_press', cat: 'empujes', pat: 'empuje_v', equipo: 'Barra olímpica',
    nombre: 'Cargada y press con barra',
    p: ['hombros', 'triceps'], s: ['trapecios', 'lumbares', 'gluteos', 'agarre'], esq: ['cinco', 'simples'],
    tip: 'Del suelo a los hombros y arriba. Calienta el cuerpo entero y, cargada, es un ejercicio en serio.' },
  { id: 'push_press', cat: 'empujes', pat: 'empuje_v', equipo: 'Jaula + barra',
    nombre: 'Push press (empuje con piernas)',
    p: ['hombros', 'triceps'], s: ['cuadriceps', 'core', 'trapecios'], esq: ['cinco', 'escalera'],
    tip: 'Una pequeña flexión de rodillas y empuja. Mueves más que en el press estricto: acostumbra los hombros a la carga.' },
  { id: 'press_banca', base: true, cat: 'empujes', pat: 'empuje_h', equipo: 'Banco + barra',
    nombre: 'Press de banca',
    p: ['pecho', 'triceps'], s: ['hombros'], esq: ['cinco', 'simples', 'escalera'],
    tip: 'Pies firmes, omóplatos juntos y la barra al pecho sin rebotarla. Arma los seguros de la jaula: entrenas solo.' },
  { id: 'press_banca_abajo', cat: 'empujes', pat: 'empuje_h', equipo: 'Banco + jaula + barra',
    nombre: 'Press de banca desde abajo',
    p: ['pecho', 'triceps'], s: ['hombros'], esq: ['simples'],
    tip: 'El banco dentro de la jaula y la barra apoyada en los seguros, rozando el pecho. Cada repetición parte desde abajo, sin la ayuda del rebote: la forma más dura de hacer banca, y la favorita de Kubik.' },
  { id: 'press_banca_parcial', cat: 'empujes', pat: 'empuje_h', equipo: 'Banco + jaula + barra',
    nombre: 'Press de banca parcial (últimos 10 cm)',
    p: ['triceps', 'pecho'], s: ['hombros'], esq: ['parcial', 'simples'],
    tip: 'Seguros para que la barra recorra solo los últimos 10 centímetros. Aquí se carga más que en la banca completa: los tendones también se entrenan.' },
  { id: 'press_cerrado', cat: 'empujes', pat: 'empuje_h', equipo: 'Banco + barra',
    nombre: 'Press de banca con agarre cerrado',
    p: ['triceps', 'pecho'], s: ['hombros'], esq: ['cinco', 'ocho'],
    tip: 'Manos al ancho de los hombros y codos cerca del cuerpo. Tríceps a fondo y sin aislar nada.' },
  { id: 'floor_press', cat: 'empujes', pat: 'empuje_h', equipo: 'Jaula + barra',
    nombre: 'Press desde el suelo',
    p: ['pecho', 'triceps'], s: ['hombros'], esq: ['cinco', 'simples'],
    tip: 'Acostado en el suelo dentro de la jaula: los codos tocan y la barra sube sin rebote. Buena variante cuando el hombro reclama en la banca.' },
  { id: 'fondos_anillas', cat: 'empujes', pat: 'empuje_h', equipo: 'Anillas',
    nombre: 'Fondos en anillas',
    p: ['pecho', 'triceps'], s: ['hombros', 'core'], esq: ['maxreps', 'cinco'],
    tip: 'Más duros que en paralelas: las anillas se mueven y obligan a estabilizar todo. Arriba, brazos bloqueados y anillas pegadas al cuerpo.' },
  { id: 'dips', base: true, cat: 'empujes', pat: 'empuje_h', equipo: 'Barra de fondos',
    nombre: 'Fondos en paralelas',
    p: ['pecho', 'triceps'], s: ['hombros'], esq: ['maxreps'],
    tip: 'Baja hasta que los hombros queden bajo los codos. Pasadas las 10 repeticiones, cuélgate un disco.' },

  /* ---------- tirones ---------- */
  { id: 'dominadas', base: true, cat: 'tirones', pat: 'tiron_v', equipo: 'Barra de dominadas',
    nombre: 'Dominadas',
    p: ['espalda'], s: ['biceps', 'agarre'], esq: ['maxreps'],
    tip: 'Desde brazos estirados hasta el mentón sobre la barra. Nada de medias repeticiones.' },
  { id: 'dominadas_toalla', cat: 'tirones', pat: 'tiron_v', equipo: 'Barra de dominadas',
    nombre: 'Dominadas con toalla (agarre grueso)',
    p: ['espalda', 'agarre'], s: ['biceps'], esq: ['maxreps'],
    tip: 'Pasa una toalla por la barra y agárrate de los extremos. Es la barra gruesa de la casa y funciona igual de bien.' },
  { id: 'dominadas_supinas', cat: 'tirones', pat: 'tiron_v', equipo: 'Barra de dominadas',
    nombre: 'Dominadas supinas',
    p: ['espalda', 'biceps'], s: ['agarre'], esq: ['maxreps'],
    tip: 'Palmas hacia ti. Espalda y bíceps en el mismo movimiento; no hacen falta curls de concentración.' },
  { id: 'remo', base: true, cat: 'tirones', pat: 'tiron_h', equipo: 'Barra olímpica',
    nombre: 'Remo con barra',
    p: ['espalda'], s: ['biceps', 'lumbares', 'trapecios', 'agarre'], esq: ['cinco', 'ocho'],
    tip: 'Piernas algo dobladas y espalda recta. Tira hacia la parte baja del abdomen, no hacia el pecho.' },
  { id: 'remo_anillas', cat: 'tirones', pat: 'tiron_h', equipo: 'Anillas', planB: true,
    nombre: 'Remo invertido en anillas',
    p: ['espalda'], s: ['biceps', 'core'], esq: ['maxreps', 'ocho'],
    tip: 'Cuerpo derecho como una tabla y tira el pecho hacia las anillas. Más horizontal, más difícil. Plan B cuando la espalda baja está cansada.' },
  { id: 'remo_cuello', cat: 'tirones', pat: 'trapecio', equipo: 'Barra olímpica',
    nombre: 'Remo al cuello',
    p: ['trapecios', 'hombros'], s: ['biceps', 'agarre'], esq: ['ocho', 'cinco'],
    tip: 'Agarre al ancho de los hombros, no más cerrado, y sube la barra pegada al cuerpo hasta el pecho, con los codos por delante. Si el hombro pincha, no pases de ahí.' },
  { id: 'encog_trap', cat: 'tirones', pat: 'trapecio', equipo: 'Barra hexagonal',
    nombre: 'Encogimientos con barra hexagonal',
    p: ['trapecios'], s: ['agarre'], esq: ['cinco', 'maxreps'],
    tip: 'Sube los hombros hacia las orejas y sostén un segundo arriba. Pesado.' },
  { id: 'encog_maletas', cat: 'tirones', pat: 'trapecio', equipo: 'Maletas',
    nombre: 'Encogimientos con maletas',
    p: ['trapecios'], s: ['agarre'], esq: ['fijo'],
    tip: 'Una maleta en cada mano, sube los hombros y sostén arriba. El peso es fijo, así que busca repeticiones.' },

  /* ---------- tronco de 80 kg ---------- */
  { id: 'log_press', cat: 'tronco80', pat: 'empuje_v', equipo: 'Tronco',
    nombre: 'Cargada y press con el tronco',
    p: ['hombros', 'triceps'], s: ['lumbares', 'gluteos', 'trapecios', 'core'], esq: ['reloj', 'fijo'],
    tip: 'Al pecho y arriba. Un tronco no es una barra: se mueve y se resiste. Por eso sirve.' },
  { id: 'log_clean', cat: 'tronco80', pat: 'tronco_pierna', equipo: 'Tronco',
    nombre: 'Cargada del tronco al pecho',
    p: ['gluteos', 'trapecios'], s: ['lumbares', 'cuadriceps', 'biceps', 'core'], esq: ['reloj'],
    tip: 'Del suelo al pecho. El tronco pegado al cuerpo y la cadera explosiva.' },
  { id: 'log_hombro', cat: 'tronco80', pat: 'tronco_pierna', equipo: 'Tronco',
    nombre: 'Tronco al hombro',
    p: ['gluteos', 'lumbares'], s: ['trapecios', 'biceps', 'core'], esq: ['reloj'],
    tip: 'Al hombro, cambiando de lado en cada repetición. Así entrenaban los forzudos antes de que existieran las máquinas.' },
  { id: 'log_sent', grupo: 'sentadilla', cat: 'tronco80', pat: 'sentadilla', equipo: 'Tronco',
    nombre: 'Sentadilla con el tronco al pecho',
    p: ['cuadriceps', 'gluteos'], s: ['core', 'lumbares', 'biceps', 'espalda'], esq: ['fijo'],
    tip: 'Sostenlo abrazado contra el pecho y haz sentadilla. Piernas, espalda y brazos a la vez.' },
  { id: 'log_carry', cat: 'tronco80', pat: 'acarreo', equipo: 'Tronco',
    nombre: 'Acarreo del tronco (abrazo de oso)',
    p: ['core', 'lumbares'], s: ['biceps', 'espalda', 'trapecios'], esq: ['distancia'],
    tip: 'Abrázalo contra el pecho y camina. A los 20 metros vas a entender por qué los antiguos eran tan fuertes.' },

  /* ---------- agarre y acarreos ---------- */
  { id: 'farmer_maletas', cat: 'agarre', pat: 'acarreo', equipo: 'Maletas',
    nombre: 'Paseo del granjero con maletas',
    p: ['agarre', 'trapecios'], s: ['core', 'pantorrillas', 'lumbares'], esq: ['distancia'],
    tip: 'Una maleta en cada mano y camina. No hay ejercicio más honesto que este.' },
  { id: 'farmer_trap', cat: 'agarre', pat: 'acarreo', equipo: 'Barra hexagonal',
    nombre: 'Paseo del granjero con barra hexagonal',
    p: ['agarre', 'trapecios'], s: ['core', 'pantorrillas', 'lumbares'], esq: ['distancia'],
    tip: 'Más pesado que las maletas. Espalda derecha, pasos cortos y rápidos, y no sueltes hasta llegar.' },
  { id: 'maleta_una', cat: 'agarre', pat: 'acarreo', equipo: 'Maletas',
    nombre: 'Acarreo con una maleta',
    p: ['core', 'agarre'], s: ['trapecios', 'lumbares'], esq: ['lado'],
    tip: 'Una sola maleta y el cuerpo derecho, sin inclinarte. El abdomen trabaja para que no te vayas de lado.' },
  { id: 'colgado', cat: 'agarre', pat: 'agarre', equipo: 'Barra de dominadas',
    nombre: 'Colgarse de la barra hasta caer',
    p: ['agarre'], s: [], esq: ['tiempo'],
    tip: 'Cuélgate hasta que los dedos se abran solos. Con toalla, el doble de duro.' },
  { id: 'sosten_maletas', cat: 'agarre', pat: 'agarre', equipo: 'Maletas',
    nombre: 'Sostén estático con maletas',
    p: ['agarre'], s: ['trapecios'], esq: ['tiempo'],
    tip: 'Levanta las maletas y aguanta de pie todo lo que puedas. Cronométrate.' },
  { id: 'sosten_trap', cat: 'agarre', pat: 'agarre', equipo: 'Barra hexagonal',
    nombre: 'Sostén estático con barra hexagonal',
    p: ['agarre'], s: ['trapecios'], esq: ['tiempo'],
    tip: 'Cárgala pesado, levántala y aguanta. Intenta ganarle al intento anterior.' },
  { id: 'pinza', cat: 'agarre', pat: 'agarre', equipo: 'Discos',
    nombre: 'Agarre de pinza con discos',
    p: ['agarre'], s: [], esq: ['tiempo'],
    tip: 'Dos discos juntos con el lado liso hacia afuera, pellizcados entre el pulgar y los dedos. El pulgar es la mitad del agarre.' },

  /* ---------- brazos ---------- */
  { id: 'curl', cat: 'brazos', pat: 'brazos', equipo: 'Barra olímpica',
    nombre: 'Curl con barra (con toalla para engrosar)',
    p: ['biceps'], s: ['agarre'], esq: ['ocho', 'cinco'],
    tip: 'Con una toalla envuelta en la barra, el curl también trabaja el agarre. Estricto, sin balanceo.' },
  { id: 'curl_inv', cat: 'brazos', pat: 'brazos', equipo: 'Barra olímpica',
    nombre: 'Curl invertido',
    p: ['agarre', 'biceps'], s: [], esq: ['ocho'],
    tip: 'Palmas hacia abajo. Antebrazos y bíceps a la vez; mañana vas a saber exactamente dónde trabajó.' },

  /* ---------- abdomen ---------- */
  { id: 'elev_piernas', cat: 'abdomen', pat: 'core', equipo: 'Barra de dominadas',
    nombre: 'Elevaciones de piernas colgado',
    p: ['core'], s: ['agarre'], esq: ['maxreps'],
    tip: 'Colgado de la barra, sube las piernas hasta la horizontal o más. De paso trabajan las manos.' },
  { id: 'sit_up', cat: 'abdomen', pat: 'core', equipo: 'Disco',
    nombre: 'Abdominales con rodillas dobladas y disco',
    p: ['core'], s: [], esq: ['abdominal'],
    tip: 'Rodillas dobladas y un disco detrás de la cabeza. Abdomen de los que sirven para algo.' },
  { id: 'flexion_lateral', cat: 'abdomen', pat: 'core', equipo: 'Disco o maleta',
    nombre: 'Flexión lateral',
    p: ['core'], s: [], esq: ['abdominal'],
    tip: 'Un disco o una maleta en una mano, inclínate hacia ese lado y vuelve. Después el otro.' },
  { id: 'giro_barra', cat: 'abdomen', pat: 'core', equipo: 'Barra olímpica anclada',
    nombre: 'Giro con barra anclada (full contact twist)',
    p: ['core'], s: ['hombros', 'gluteos'], esq: ['ocho'],
    tip: 'Una punta de la barra en una esquina (con una toalla) y un disco en la otra. Brazos estirados, llévala de un lado a otro girando el tronco y pivoteando el pie de atrás. Cuenta cada lado como una. Parte liviano: la fuerza sale de la cadera, no de los brazos.' },
  { id: 'turca', cat: 'abdomen', pat: 'core', equipo: 'Disco',
    nombre: 'Levantada turca con disco',
    p: ['core'], s: ['hombros', 'gluteos'], esq: ['turca'],
    tip: 'Acostado, con un disco arriba y el brazo estirado: ponte de pie sin bajarlo y vuelve al suelo. Lento.' },
  { id: 'rueda', cat: 'abdomen', pat: 'core', equipo: 'Rueda abdominal',
    nombre: 'Rueda abdominal de rodillas',
    p: ['core'], s: ['hombros', 'espalda'], esq: ['ocho', 'maxreps'],
    tip: 'De rodillas sobre algo blando, rueda adelante con los brazos estirados y la cadera metida, hasta donde puedas volver sin arquear la cintura. Vuelve tirando con el abdomen, no con la cadera. Cuando salgan 15 limpias, prueba de pie.' },
  { id: 'rueda_pie', cat: 'abdomen', pat: 'core', equipo: 'Rueda abdominal', kubik: false,
    nombre: 'Rueda abdominal de pie',
    p: ['core'], s: ['hombros', 'espalda'], esq: ['maxreps'],
    tip: 'La versión de los fuertes: de pie, piernas estiradas, rueda hasta quedar casi en el suelo y vuelve. Para aprender, rueda hacia la pared de la jaula para que te frene antes.' },

  /* ---------- cuello ---------- */
  { id: 'cuello_arnes', base: true, cat: 'cuello', pat: 'cuello', equipo: 'Arnés de cuello + discos',
    nombre: 'Extensión de cuello con arnés',
    p: ['cuello'], s: ['trapecios'], esq: ['cuello'],
    tip: 'De pie, inclinado hacia adelante con las manos en las rodillas y el disco colgando del arnés. Baja el mentón al pecho y sube la cabeza hasta mirar al frente. Kubik: un cuello grueso es la marca de un hombre fuerte, y protege la columna.' },
  { id: 'cuello_arnes_sosten', cat: 'cuello', pat: 'cuello', equipo: 'Arnés de cuello + discos',
    nombre: 'Sostén con arnés de cuello',
    p: ['cuello'], s: ['trapecios'], esq: ['tiempo'],
    tip: 'Con más peso que en las extensiones, cabeza derecha y a aguantar. Isométrico, como las viejas pruebas de los forzudos.' },
  { id: 'cuello_disco', cat: 'cuello', pat: 'cuello', equipo: 'Banco + disco',
    nombre: 'Flexión de cuello con disco',
    p: ['cuello'], s: [], esq: ['cuello'],
    tip: 'Acostado de espalda en el banco con la cabeza afuera y un disco chico sobre la frente (con una toalla). Mentón al pecho y vuelve. Equilibra el trabajo del arnés, que es para la nuca.' },

  /* ---------- poleas: complementos y planes B ---------- */
  { id: 'jalon_larga', cat: 'poleas', pat: 'tiron_v', equipo: 'Polea alta · barra larga', planB: true,
    nombre: 'Jalón con barra larga',
    p: ['espalda'], s: ['biceps'], esq: ['cinco', 'ocho'],
    tip: 'Plan B para cuando las dominadas no dan. Tira al pecho y controla la vuelta.' },
  { id: 'jalon_cerrado', cat: 'poleas', pat: 'tiron_v', equipo: 'Polea alta · agarre cerrado', planB: true,
    nombre: 'Jalón con agarre cerrado',
    p: ['espalda'], s: ['biceps'], esq: ['ocho'],
    tip: 'Codos hacia abajo y pegados al cuerpo. Otro plan B cuando la barra fija ya te venció.' },
  { id: 'remo_cerrado', cat: 'poleas', pat: 'tiron_h', equipo: 'Polea baja · agarre cerrado', planB: true,
    nombre: 'Remo en polea baja con agarre cerrado',
    p: ['espalda'], s: ['biceps', 'trapecios'], esq: ['cinco', 'ocho'],
    tip: 'Pecho arriba y tira al ombligo. Sirve cuando la espalda baja está cansada y el remo con barra queda vetado.' },
  { id: 'remo_cuello_polea', cat: 'poleas', pat: 'trapecio', equipo: 'Polea baja · barra corta', planB: true,
    nombre: 'Remo al cuello en polea',
    p: ['trapecios', 'hombros'], s: ['biceps', 'agarre'], esq: ['ocho', 'complemento'],
    tip: 'Como el de barra, pero la polea tira parejo todo el recorrido. Agarre al ancho de los hombros, codos por delante y hasta el pecho. Si el hombro pincha, no subas más.' },
  { id: 'remo_larga', cat: 'poleas', pat: 'tiron_h', equipo: 'Polea baja · barra larga', planB: true,
    nombre: 'Remo en polea baja con barra larga',
    p: ['espalda'], s: ['biceps', 'trapecios'], esq: ['ocho'],
    tip: 'Agarre ancho y codos afuera. Plan B para la espalda alta.' },
  { id: 'remo_v', cat: 'poleas', pat: 'tiron_h', equipo: 'Polea baja · agarre en V', planB: true,
    nombre: 'Remo en polea baja con agarre en V',
    p: ['espalda'], s: ['biceps', 'trapecios', 'agarre'], esq: ['cinco', 'ocho'],
    tip: 'Manos enfrentadas y el agarre gira con la muñeca, así que el codo y el hombro van cómodos. Pecho arriba, tira hasta tocarte el abdomen y aprieta los omóplatos. Plan B cuando la espalda baja está cansada.' },
  { id: 'jalon_v', cat: 'poleas', pat: 'tiron_v', equipo: 'Polea alta · agarre en V', planB: true,
    nombre: 'Jalón con agarre en V',
    p: ['espalda'], s: ['biceps', 'agarre'], esq: ['cinco', 'ocho'],
    tip: 'Agarre neutro: el más amable con los codos de todos los jalones. Inclínate un poco atrás y tira hasta la parte alta del pecho. Plan B para las dominadas.' },
  { id: 'curl_cuerda', cat: 'poleas', pat: 'brazos', equipo: 'Polea baja · cuerda',
    nombre: 'Curl de bíceps con cuerda en polea',
    p: ['biceps'], s: ['agarre'], esq: ['ocho', 'complemento'],
    tip: 'Codos quietos y aprieta arriba. Los brazos grandes salen de los tirones pesados; esto es el remate.' },
  { id: 'curl_martillo_cuerda', cat: 'poleas', pat: 'brazos', equipo: 'Polea baja · 2 cuerdas',
    nombre: 'Curl martillo con cuerdas',
    p: ['biceps', 'agarre'], s: [], esq: ['complemento'],
    tip: 'Con las dos cuerdas y los pulgares arriba: bíceps y antebrazo a la vez.' },
  { id: 'curl_polea', cat: 'poleas', pat: 'brazos', equipo: 'Polea baja · barra corta', kubik: false,
    nombre: 'Curl en polea con barra corta',
    p: ['biceps'], s: [], esq: ['complemento'],
    tip: 'Si ya hiciste dominadas pesadas, puedes saltártelo sin culpa.' },
  { id: 'triceps_cuerda', cat: 'poleas', pat: 'brazos', equipo: 'Polea alta · cuerda',
    nombre: 'Extensión de tríceps con cuerda',
    p: ['triceps'], s: [], esq: ['ocho', 'complemento'],
    tip: 'Codos pegados y abre la cuerda abajo. El trabajo grande ya lo hicieron los presses y los fondos; esto es el remate.' },
  { id: 'triceps_v', cat: 'poleas', pat: 'brazos', equipo: 'Polea alta · agarre en V',
    nombre: 'Extensión de tríceps con agarre en V',
    p: ['triceps'], s: [], esq: ['ocho', 'complemento'],
    tip: 'Codos pegados al cuerpo y quietos; empuja hasta estirar los brazos del todo. El agarre giratorio no le pide nada a la muñeca: buena opción si la barra corta molesta.' },
  { id: 'triceps_barra', cat: 'poleas', pat: 'brazos', equipo: 'Polea alta · barra corta', kubik: false,
    nombre: 'Extensión de tríceps con barra corta',
    p: ['triceps'], s: [], esq: ['complemento'],
    tip: 'Complemento. Codos quietos y pegados al cuerpo.' },
  { id: 'face_pull', cat: 'poleas', pat: 'hombro_salud', equipo: 'Polea alta · cuerda', kubik: false,
    nombre: 'Face pull con cuerda',
    p: ['hombros'], s: ['trapecios'], esq: ['complemento'],
    tip: 'Para la salud de los hombros. No reemplaza a ningún press.' },
  { id: 'crunch_polea', cat: 'poleas', pat: 'core', equipo: 'Polea alta · cuerda', kubik: false,
    nombre: 'Crunch de rodillas con cuerda',
    p: ['core'], s: [], esq: ['complemento'],
    tip: 'Abdomen de rodillas y con peso.' },
  { id: 'pull_through', cat: 'poleas', pat: 'bisagra', equipo: 'Polea baja · cuerda', kubik: false,
    nombre: 'Pull-through con cuerda',
    p: ['gluteos'], s: ['lumbares'], esq: ['complemento'],
    tip: 'Cadera atrás y empuja con los glúteos. Complemento para después del peso muerto.' },

  /* ---------- tobillera en la polea baja ---------- */
  { id: 'patada_gluteo', cat: 'tobillera', pat: 'bisagra', equipo: 'Polea baja · tobillera', kubik: false,
    nombre: 'Patada de glúteo en polea',
    p: ['gluteos'], s: ['lumbares'], esq: ['complemento'],
    tip: 'Frente a la polea, agarrado de la jaula: lleva la pierna atrás estirada apretando el glúteo, sin arquear la cintura. Vuelve lento. Las dos piernas.' },
  { id: 'curl_femoral_pie', cat: 'tobillera', pat: 'bisagra', equipo: 'Polea baja · tobillera', kubik: false,
    nombre: 'Curl femoral de pie en polea',
    p: ['gluteos'], s: ['pantorrillas'], esq: ['complemento'],
    tip: 'Frente a la polea, la rodilla quieta apuntando al suelo: dobla la pierna llevando el talón al glúteo. Trabaja los isquios sin cargar la espalda.' },
  { id: 'abduccion_polea', cat: 'tobillera', pat: 'bisagra', equipo: 'Polea baja · tobillera', kubik: false,
    nombre: 'Abducción de cadera en polea',
    p: ['gluteos'], s: [], esq: ['complemento'],
    tip: 'De costado, con la tobillera en la pierna de afuera: llévala hacia el lado, lejos de la polea, sin inclinar el tronco. Glúteo medio, el que sostiene la rodilla en la sentadilla.' },
  { id: 'aduccion_polea', cat: 'tobillera', pat: 'bisagra', equipo: 'Polea baja · tobillera', kubik: false,
    nombre: 'Aducción de cadera en polea',
    p: [], s: ['gluteos'], esq: ['complemento'],
    tip: 'De costado, con la tobillera en la pierna más cercana a la polea: crúzala por delante de la otra. Aductores, la cara interna del muslo; ayudan a salir del fondo de la sentadilla.' },
  { id: 'elev_rodilla_polea', cat: 'tobillera', pat: 'core', equipo: 'Polea baja · tobillera', kubik: false,
    nombre: 'Elevación de rodilla en polea',
    p: ['core'], s: [], esq: ['complemento'],
    tip: 'De espaldas a la polea: sube la rodilla hasta la cadera o más arriba, sin echar el tronco atrás. Flexores de la cadera y abdomen bajo.' },

  /* ---------- banda de resistencia ---------- */
  { id: 'pallof', cat: 'banda', pat: 'core', equipo: 'Banda atada a la jaula',
    nombre: 'Press Pallof con banda',
    p: ['core'], s: [], esq: ['ocho'],
    tip: 'De costado a la jaula, con la banda tensa a la altura del pecho: estira los brazos al frente, aguanta 2 segundos sin dejar que te gire y vuelve. 8 a 10 por lado. Abdomen que no carga la columna: sirve aunque la espalda baja reclame.' },
  { id: 'pull_apart', cat: 'banda', pat: 'hombro_salud', equipo: 'Banda', kubik: false,
    nombre: 'Separación de banda (pull-apart)',
    p: ['hombros'], s: ['trapecios'], esq: ['complemento'],
    tip: 'Brazos estirados al frente y abre la banda hasta tocarte el pecho, juntando los omóplatos. Para la salud de los hombros: unas 20 antes de los presses son el mejor calentamiento.' },
  { id: 'dominadas_banda', cat: 'banda', pat: 'tiron_v', equipo: 'Barra de dominadas + banda', kubik: false,
    nombre: 'Dominadas asistidas con banda',
    p: ['espalda'], s: ['biceps', 'agarre'], esq: ['maxreps', 'ocho'],
    tip: 'La banda colgada de la barra y una rodilla o los pies dentro. Para sumar repeticiones cuando las dominadas ya no salen, o para los WOD con muchas. La meta es dejarla.' },
  { id: 'pm_bandas', grupo: 'peso_muerto', cat: 'banda', pat: 'bisagra', equipo: 'Barra olímpica + banda', kubik: false,
    nombre: 'Peso muerto con banda',
    p: ['gluteos', 'lumbares'], s: ['espalda', 'trapecios', 'agarre', 'cuadriceps'], esq: ['cinco', 'simples'],
    tip: 'La banda pisada por el medio y sus puntas sobre la barra: arriba pesa más que abajo y te obliga a terminar el tirón con fuerza. Usa menos disco que en el peso muerto normal.' },

  /* ---------- calentamiento ---------- */
  { id: 'cuerda', cat: 'otros', pat: 'calentar', equipo: 'Cuerda',
    nombre: 'Saltar la cuerda',
    p: [], s: ['pantorrillas'], esq: ['calentar'],
    tip: 'Suave, de 2 a 5 minutos. Es para entrar en calor, no para cansarte: guarda la energía para el hierro.' },
  { id: 'burpees', cat: 'otros', pat: 'acondicionamiento', equipo: 'Peso corporal',
    nombre: 'Burpees',
    p: [], s: ['cuadriceps', 'pecho', 'triceps', 'hombros', 'core'], esq: ['burpees'],
    tip: 'Al suelo, pecho abajo, arriba y salto. Kubik habría cargado un saco de arena, pero terminas en el mismo lugar: sin aire y con ganas de parar. No pares.' },
  /* ---------- movimientos de CrossFit (para los WOD) ---------- */
  { id: 'thruster', cat: 'crossfit', pat: 'empuje_v', equipo: 'Barra olímpica', kubik: false,
    nombre: 'Thruster',
    p: ['cuadriceps', 'hombros'], s: ['gluteos', 'triceps', 'core'], esq: ['maxreps'],
    tip: 'Sentadilla frontal y, al subir, el impulso de las piernas lleva la barra arriba en un solo movimiento.' },
  { id: 'cargada', cat: 'crossfit', pat: 'bisagra', equipo: 'Barra olímpica', kubik: false,
    nombre: 'Cargada de potencia (power clean)',
    p: ['gluteos', 'trapecios'], s: ['cuadriceps', 'lumbares', 'agarre', 'espalda'], esq: ['simples'],
    tip: 'Del suelo a los hombros en un tirón explosivo, recibiendo la barra en un cuarto de sentadilla con los codos altos.' },
  { id: 'arranque', cat: 'crossfit', pat: 'empuje_v', equipo: 'Barra olímpica', kubik: false,
    nombre: 'Arranque de potencia (power snatch)',
    p: ['gluteos', 'hombros', 'trapecios'], s: ['lumbares', 'cuadriceps', 'core'], esq: ['simples'],
    tip: 'Agarre ancho y del suelo a brazos estirados sobre la cabeza en un solo tirón. Parte liviano: es pura técnica.' },
  { id: 'ohs', cat: 'crossfit', pat: 'sentadilla', equipo: 'Barra olímpica', kubik: false,
    nombre: 'Sentadilla con la barra arriba (overhead squat)',
    p: ['cuadriceps', 'hombros'], s: ['gluteos', 'core', 'trapecios'], esq: ['maxreps'],
    tip: 'Barra arriba con agarre ancho y brazos bloqueados; baja con el pecho alto. Exige hombros y tobillos móviles.' },
  { id: 'hspu', cat: 'crossfit', pat: 'empuje_v', equipo: 'Pared', kubik: false,
    nombre: 'Flexiones de pino contra la pared (HSPU)',
    p: ['hombros', 'triceps'], s: ['trapecios', 'core'], esq: ['maxreps'],
    tip: 'Parado de manos con los talones en la pared: baja la cabeza a un cojín y empuja. Si no salen, flexiones con los pies en el banco.' },
  { id: 'muscle_up', cat: 'crossfit', pat: 'tiron_v', equipo: 'Anillas', kubik: false,
    nombre: 'Muscle-up en anillas',
    p: ['espalda', 'triceps'], s: ['pecho', 'biceps', 'core'], esq: ['maxreps'],
    tip: 'Agarre falso (las muñecas sobre las anillas), una dominada explosiva, pasa el pecho por encima y termina con un fondo. También se puede en la barra.' },
  { id: 'correr', cat: 'crossfit', pat: 'acondicionamiento', equipo: 'Calle', kubik: false,
    nombre: 'Correr',
    p: [], s: ['cuadriceps', 'pantorrillas', 'gluteos'], esq: ['maxreps'],
    tip: 'En los WOD, 400 m son una vuelta a la manzana más o menos. Sin lugar para correr: 2 minutos de cuerda por cada 400 m.' },
  { id: 'swing_disco', cat: 'crossfit', pat: 'bisagra', equipo: 'Disco', kubik: false,
    nombre: 'Swing con disco (en vez de pesa rusa)',
    p: ['gluteos'], s: ['lumbares', 'hombros', 'agarre'], esq: ['maxreps'],
    tip: 'Un disco tomado por los costados, entre las piernas, y un golpe de cadera lo sube a la altura de los ojos. Los brazos no tiran.' },
  { id: 'salto_cajon', cat: 'crossfit', pat: 'acondicionamiento', equipo: 'Banco firme o suelo', kubik: false,
    nombre: 'Salto al cajón (o al banco)',
    p: [], s: ['cuadriceps', 'gluteos', 'pantorrillas'], esq: ['maxreps'],
    tip: 'Salta con los dos pies y cae suave arriba, de pie del todo; baja caminando. Si el banco no es firme, saltos de sentadilla.' },
  { id: 'pistol', cat: 'crossfit', pat: 'sentadilla', equipo: 'Peso corporal', kubik: false,
    nombre: 'Sentadilla a una pierna (pistol)',
    p: ['cuadriceps', 'gluteos'], s: ['core'], esq: ['maxreps'],
    tip: 'Una pierna estirada adelante y baja con la otra hasta abajo. Para aprender, agárrate de la jaula.' },
  /* ---------- peso corporal (sobre todo para la Baraja) ---------- */
  { id: 'flexiones', cat: 'otros', pat: 'empuje_h', equipo: 'Peso corporal', kubik: false,
    nombre: 'Flexiones de brazos',
    p: ['pecho', 'triceps'], s: ['hombros', 'core'], esq: ['maxreps'],
    tip: 'Cuerpo derecho como una tabla, manos algo más anchas que los hombros. Pecho hasta el suelo y arriba sin arquear la cintura.' },
  { id: 'sentadilla_libre', cat: 'otros', pat: 'sentadilla', equipo: 'Peso corporal', kubik: false,
    nombre: 'Sentadillas sin peso',
    p: ['cuadriceps', 'gluteos'], s: [], esq: ['maxreps'],
    tip: 'Pies al ancho de los hombros, baja hasta la paralela con el pecho arriba y sube con fuerza.' },
  { id: 'saltos_estrella', cat: 'otros', pat: 'acondicionamiento', equipo: 'Peso corporal', kubik: false,
    nombre: 'Saltos de estrella',
    p: [], s: ['cuadriceps', 'pantorrillas', 'hombros'], esq: ['maxreps'],
    tip: 'Agáchate un poco y salta abriendo brazos y piernas como una estrella. Cae suave, juntando todo.' },
  { id: 'escaladores', cat: 'otros', pat: 'acondicionamiento', equipo: 'Peso corporal', kubik: false,
    nombre: 'Escaladores',
    p: ['core'], s: ['hombros', 'cuadriceps'], esq: ['maxreps'],
    tip: 'En plancha, lleva una rodilla al pecho y cámbiala rápido por la otra, como si corrieras. Cadera baja.' },
];

/* Cómo arma Kubik cada tipo de día. Cada casillero pide un patrón; la app
   elige el mejor ejercicio disponible según lo que está descansado. */
const PLANTILLAS = {
  inferior: {
    titulo: 'Piernas, cadera y espalda baja',
    intro: 'De aquí sale toda la fuerza. Pocos ejercicios, todos pesados, y el último te deja en el suelo.',
    casilleros: [
      ['sentadilla', 'bisagra', 'tronco_pierna'],
      ['bisagra', 'sentadilla', 'parcial', 'tronco_pierna'],
      ['acarreo'],
      ['pantorrilla'],
      ['agarre'],
      ['core'],
    ],
  },
  superior: {
    titulo: 'Torso y brazos',
    intro: 'Empuja, tira y termina con las manos destrozadas. Si te sobra energía al final, no entrenaste lo bastante pesado.',
    casilleros: [
      ['empuje_v', 'empuje_h'],
      ['tiron_v', 'tiron_h'],
      ['empuje_h', 'empuje_v'],
      ['tiron_h', 'tiron_v', 'trapecio'],
      ['cuello'],
      ['brazos'],
      ['brazos', 'agarre'],
      ['core'],
    ],
  },
  completo: {
    titulo: 'Cuerpo completo',
    intro: 'La versión corta: un levantamiento grande de piernas, un empuje, un tirón y agarre. Entras, lo das todo y te vas.',
    casilleros: [
      ['sentadilla', 'bisagra', 'tronco_pierna'],
      ['empuje_v', 'empuje_h'],
      ['tiron_v', 'tiron_h'],
      ['acarreo', 'agarre'],
      ['cuello'],
      ['core'],
      ['acondicionamiento'],
    ],
  },
  corto: {
    titulo: 'Agarre, cuello y abdomen',
    intro: 'Piernas y torso siguen reconstruyéndose. Hoy van las manos, el cuello y el abdomen, que se recuperan rápido, y a la casa.',
    casilleros: [
      ['acarreo', 'agarre'],
      ['agarre'],
      ['cuello'],
      ['core'],
      ['pantorrilla'],
      ['acondicionamiento'],
    ],
  },
};

const FRASES = [
  'Pesado, simple y constante. Lo demás es adorno.',
  'Entrena duro o entrena mucho. Las dos cosas no se pueden.',
  'La barra no sabe cuánto te costó llegar. Solo sabe si la levantas.',
  'Un ejercicio que te deja en el suelo vale más que diez que te dejan congestionado.',
  'Tus manos son el eslabón más débil. Por eso se entrenan siempre.',
  'Si el último entrenamiento fue fácil, no fue entrenamiento.',
  'El descanso no es flojera. Es donde se cobra el trabajo.',
  'Nadie se hizo fuerte con máquinas cromadas. Se hizo fuerte levantando cosas pesadas.',
  'Un día más de descanso no le hace daño a nadie que esté construyendo músculo de verdad.',
  'No hay esquema de series que sirva si no entrenas duro.',
];

const PRINCIPIOS = [
  ['Trabajo duro', 'Nada de lo que diga esta app sirve si no entrenas duro. Cada serie importante es una pelea.'],
  ['Ejercicios básicos', 'Sentadilla, peso muerto, press, dominadas, fondos, remos. Los de aislamiento son decoración.'],
  ['Entrenamiento corto', 'Pocos ejercicios, pocas series, y días de descanso. Duro y mucho no se pueden a la vez.'],
  ['Pesado y cada vez más', 'Pesado es lo máximo que puedes mover bien. Cuando salgan las repeticiones, ponle más.'],
  ['Tu propio esquema', 'Hay quien crece con 5 × 5, quien crece con simples y quien crece con una serie a muerte. Prueba y quédate con lo que te funciona.'],
  ['Agarre grueso', 'Una toalla envuelta en la barra hace todo más difícil, y por eso mejor.'],
  ['Agarre, siempre', 'Maletas, colgarse, pinza con discos. Unas manos fuertes sirven en cualquier deporte y en la vida.'],
  ['Objetos incómodos', 'El tronco de 80 kg se mueve, rueda y se resiste. Enseña cosas que la barra no enseña.'],
  ['Cuello de luchador', 'Los forzudos y luchadores de antes entrenaban el cuello con arnés. Un cuello fuerte protege la columna y se nota.'],
  ['Sentadilla o peso muerto', 'Nunca los dos el mismo día: cada uno pide todo lo que tienes. Se turnan, uno por sesión de piernas.'],
  ['La jaula', 'Sentadillas desde abajo y parciales pesadas: la jaula no es solo para colgar la barra.'],
  ['Concentración', 'Durante la serie no existe nada más. Ni el teléfono.'],
];

/* Zonas que se pueden marcar con dolor en «Lesión o dolor»: articulaciones y
   tendones que más se lesionan entrenando pesado, y los ejercicios que las
   cargan. Un músculo con dolor deja fuera todo ejercicio que lo use (de
   principal o de rebote); una zona de aquí, los ejercicios de su lista. */
const SENTADILLAS = ['sent_abajo', 'sent', 'sent_frontal', 'cuarto_sent', 'log_sent', 'zancadas_maletas', 'sentadilla_libre', 'thruster', 'ohs', 'pistol'];
const PESOS_MUERTOS = ['pm_trap', 'pm', 'pm_bandas', 'pm_parcial', 'pm_maletas', 'pm_rumano', 'cargada', 'arranque', 'swing_disco'];
const BARRA_EN_ESPALDA = ['sent', 'sent_abajo', 'cuarto_sent', 'talones', 'buenos_dias'];
const PRESS_ARRIBA = ['press_pie', 'press_frente', 'cargada_press', 'push_press', 'log_press', 'thruster', 'arranque', 'ohs', 'hspu'];
const PRESS_BANCA = ['press_banca', 'press_banca_abajo', 'press_banca_parcial', 'press_cerrado', 'floor_press', 'dips', 'fondos_anillas', 'flexiones', 'escaladores'];
const DOMINADAS = ['dominadas', 'dominadas_toalla', 'dominadas_supinas', 'jalon_larga', 'jalon_cerrado', 'jalon_v', 'muscle_up', 'remo_anillas', 'dominadas_banda'];
const CURLS = ['curl', 'curl_inv', 'curl_cuerda', 'curl_martillo_cuerda', 'curl_polea'];
const TRONCO_ABRAZADO = ['log_clean', 'log_hombro', 'log_carry', 'log_sent'];
const ACARREOS = ['farmer_maletas', 'farmer_trap', 'maleta_una', 'log_carry'];
/* Todo lo que exige apretar fuerte con las manos: los tendones del codo y
   del antebrazo lo sienten aunque el ejercicio sea de piernas. */
const AGARRE_FUERTE = EJERCICIOS.filter(e => [...e.p, ...(e.s || [])].includes('agarre')).map(e => e.id);

const REGIONES_LESION = [
  { id: 'brazo', nombre: 'Hombro, codo y muñeca' },
  { id: 'espalda', nombre: 'Cuello y espalda' },
  { id: 'pierna', nombre: 'Cadera, rodilla y pie' },
];

const ARTICULACIONES = [
  /* ---------- hombro, codo y muñeca ---------- */
  { id: 'art_hombro', region: 'brazo', nombre: 'Hombro (articulación)', corto: 'Hombro',
    ayuda: 'Dolor dentro del hombro o al levantar el brazo sobre la cabeza.',
    ej: [...PRESS_ARRIBA, ...PRESS_BANCA, ...DOMINADAS, ...BARRA_EN_ESPALDA, 'remo_cuello', 'remo_cuello_polea', 'log_clean', 'face_pull', 'pull_apart', 'rueda', 'rueda_pie', 'turca', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'elev_piernas', 'colgado'] },
  { id: 'ten_biceps_hombro', region: 'brazo', nombre: 'Tendón del bíceps en el hombro', corto: 'Bíceps (hombro)',
    ayuda: 'Adelante del hombro, en la canaleta donde nace el bíceps. Duele en la banca y los fondos.',
    ej: [...PRESS_BANCA, ...CURLS, 'dominadas_supinas', 'remo_cuello', 'remo_cuello_polea', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'sent_frontal', ...TRONCO_ABRAZADO] },
  { id: 'ten_codo_int', region: 'brazo', nombre: 'Codo por dentro (codo de golfista)', corto: 'Codo interno',
    ayuda: 'Lado interno del codo, entre el bíceps y el antebrazo. Se agrava con todo lo que exige agarre: peso muerto, acarreos, dominadas, curls.',
    ej: [...AGARRE_FUERTE, ...PESOS_MUERTOS, ...CURLS, ...DOMINADAS, ...TRONCO_ABRAZADO, ...ACARREOS, 'remo', 'remo_cerrado', 'remo_larga', 'press_cerrado', 'remo_v'] },
  { id: 'ten_codo_ext', region: 'brazo', nombre: 'Codo por fuera (codo de tenista)', corto: 'Codo externo',
    ayuda: 'Lado externo del codo. Duele al agarrar con la palma hacia abajo: remos, curl invertido, peso muerto.',
    ej: [...AGARRE_FUERTE, ...PESOS_MUERTOS, ...DOMINADAS, ...ACARREOS, 'remo', 'remo_cerrado', 'remo_larga', 'curl_inv', 'curl_martillo_cuerda', 'triceps_barra', 'log_clean', 'log_hombro', 'remo_v'] },
  { id: 'ten_codo_atras', region: 'brazo', nombre: 'Codo por detrás (tríceps)', corto: 'Codo atrás',
    ayuda: 'La punta del codo o justo encima. Duele al estirar el brazo con carga: press, fondos, extensiones.',
    ej: [...PRESS_ARRIBA, ...PRESS_BANCA, 'triceps_cuerda', 'triceps_barra', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'turca', 'triceps_v'] },
  { id: 'art_muneca', region: 'brazo', nombre: 'Muñeca', corto: 'Muñeca',
    ayuda: 'Dolor al doblar la muñeca hacia atrás con peso o al apretar.',
    ej: [...PRESS_ARRIBA, ...PRESS_BANCA, 'sent_frontal', 'curl', 'curl_inv', 'pinza', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'turca',
      'farmer_maletas', 'farmer_trap', 'sosten_maletas', 'sosten_trap', 'flexion_lateral'] },
  { id: 'art_pulgar', region: 'brazo', nombre: 'Pulgar y dedos', corto: 'Dedos',
    ayuda: 'Base del pulgar o dedos resentidos. Pinza, sostenes y acarreos los castigan.',
    ej: [...AGARRE_FUERTE, ...ACARREOS] },

  /* ---------- cuello y espalda ---------- */
  { id: 'art_cervical', region: 'espalda', nombre: 'Cervical (nuca)', corto: 'Cervical',
    ayuda: 'Cuello rígido o dolor en la nuca que baja hacia el hombro.',
    ej: ['cuello_arnes', 'cuello_arnes_sosten', 'cuello_disco', 'encog_trap', 'encog_maletas', ...BARRA_EN_ESPALDA, 'log_hombro', 'sit_up', 'remo_cuello', 'remo_cuello_polea'] },
  { id: 'art_dorsal', region: 'espalda', nombre: 'Espalda alta (entre los omóplatos)', corto: 'Espalda alta',
    ayuda: 'Puntada o contractura entre los omóplatos, típica después de remos o peso muerto.',
    ej: [...PESOS_MUERTOS, 'remo', 'remo_cerrado', 'remo_larga', 'encog_trap', 'encog_maletas', 'remo_cuello', 'remo_cuello_polea', ...TRONCO_ABRAZADO, ...ACARREOS, 'sent_frontal', 'remo_v'] },
  { id: 'art_columna', region: 'espalda', nombre: 'Espalda baja (columna lumbar)', corto: 'Lumbar',
    ayuda: 'Dolor en la zona lumbar, o que baja por la pierna (ciática). Todo lo pesado de pie la carga.',
    ej: [...SENTADILLAS, ...PESOS_MUERTOS, 'buenos_dias', 'remo', ...PRESS_ARRIBA, ...TRONCO_ABRAZADO, ...ACARREOS,
      'encog_trap', 'encog_maletas', 'sit_up', 'flexion_lateral', 'turca', 'cuello_arnes', 'cuello_arnes_sosten', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'pull_through', 'talones', 'giro_barra', 'rueda', 'rueda_pie', 'patada_gluteo'] },

  /* ---------- cadera, rodilla y pie ---------- */
  { id: 'art_cadera', region: 'pierna', nombre: 'Cadera', corto: 'Cadera',
    ayuda: 'Dolor profundo en la cadera, al fondo de la sentadilla o al subir la pierna.',
    ej: [...SENTADILLAS, ...PESOS_MUERTOS, 'buenos_dias', 'log_clean', 'log_hombro', 'pull_through', 'elev_piernas', 'turca', 'cargada_press', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'sit_up', 'giro_barra', 'patada_gluteo', 'abduccion_polea', 'aduccion_polea', 'elev_rodilla_polea'] },
  { id: 'art_ingle', region: 'pierna', nombre: 'Ingle (aductores)', corto: 'Ingle',
    ayuda: 'Cara interna del muslo o la ingle. Se resiente en el fondo de la sentadilla y en las zancadas.',
    ej: [...SENTADILLAS, 'pm_trap', 'pm_maletas', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'elev_piernas', 'log_clean', 'abduccion_polea', 'aduccion_polea'] },
  { id: 'ten_isquios', region: 'pierna', nombre: 'Isquiotibiales (atrás del muslo)', corto: 'Isquios',
    ayuda: 'Tirón o dolor atrás del muslo o donde se une al glúteo. Peso muerto rumano y buenos días lo estiran con carga.',
    ej: [...PESOS_MUERTOS, 'buenos_dias', 'pull_through', 'zancadas_maletas', 'log_clean', 'log_hombro', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'sent_abajo', 'curl_femoral_pie', 'patada_gluteo'] },
  { id: 'art_rodilla', region: 'pierna', nombre: 'Rodilla (articulación)', corto: 'Rodilla',
    ayuda: 'Dolor dentro de la rodilla, a los lados o al girarla.',
    ej: [...SENTADILLAS, 'pm_trap', 'pm_maletas', 'push_press', 'log_clean', ...ACARREOS, 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'cuerda', 'curl_femoral_pie'] },
  { id: 'ten_rotuliano', region: 'pierna', nombre: 'Tendón bajo la rótula', corto: 'Rotuliano',
    ayuda: 'Justo debajo de la rótula. Duele al saltar, bajar escaleras o al fondo de la sentadilla.',
    ej: [...SENTADILLAS, 'pm_trap', 'pm_maletas', 'push_press', 'log_clean', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'cuerda'] },
  { id: 'ten_aquiles', region: 'pierna', nombre: 'Tendón de Aquiles', corto: 'Aquiles',
    ayuda: 'Atrás del tobillo, sobre el talón. Saltos y elevaciones de talones lo castigan.',
    ej: ['talones', 'cuerda', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'push_press', 'zancadas_maletas', ...ACARREOS] },
  { id: 'art_tobillo', region: 'pierna', nombre: 'Tobillo', corto: 'Tobillo',
    ayuda: 'Esguince reciente o dolor al doblar el tobillo.',
    ej: [...SENTADILLAS, 'talones', 'cuerda', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'push_press', ...ACARREOS, 'patada_gluteo', 'curl_femoral_pie', 'abduccion_polea', 'aduccion_polea', 'elev_rodilla_polea'] },
  { id: 'art_pie', region: 'pierna', nombre: 'Planta del pie (fascitis)', corto: 'Planta',
    ayuda: 'Dolor en el talón por abajo, sobre todo al primer paso de la mañana.',
    ej: ['cuerda', 'burpees', 'saltos_estrella', 'escaladores', 'correr', 'salto_cajon', 'talones', ...ACARREOS, 'zancadas_maletas'] },
];

/* Zonas de versiones anteriores que ahora están divididas. */
const ZONAS_RENOMBRADAS = { art_codo: ['ten_codo_int', 'ten_codo_ext', 'ten_codo_atras'] };
