/* WOD conocidos de CrossFit: las «Chicas», los «Héroes» y otros clásicos.
   Cada movimiento apunta a un ejercicio del catálogo (para la ejecución, los
   músculos y el descanso). Si pide equipo que no hay en la casa, «falta»
   dice con qué se reemplaza. Cargas RX en kilos: hombres / mujeres. */

const MOV = {
  dominadas:    { nombre: 'Dominadas', ej: 'dominadas' },
  dom_pecho:    { nombre: 'Dominadas pecho a la barra', ej: 'dominadas' },
  dom_salto:    { nombre: 'Dominadas con salto', ej: 'dominadas' },
  flexiones:    { nombre: 'Flexiones de brazos', ej: 'flexiones' },
  abdominales:  { nombre: 'Abdominales', ej: 'sit_up' },
  sentadillas:  { nombre: 'Sentadillas sin peso', ej: 'sentadilla_libre' },
  burpees:      { nombre: 'Burpees', ej: 'burpees' },
  saltos_tij:   { nombre: 'Saltos de tijera', ej: 'saltos_estrella' },
  peso_muerto:  { nombre: 'Peso muerto', ej: 'pm' },
  hspu:         { nombre: 'Flexiones de pino (HSPU)', ej: 'hspu' },
  cargada:      { nombre: 'Cargada de potencia', ej: 'cargada' },
  cargada_sent: { nombre: 'Cargada con sentadilla', ej: 'cargada' },
  colgante:     { nombre: 'Cargada desde las rodillas (hang power clean)', ej: 'cargada' },
  envion:       { nombre: 'Cargada y envión', ej: 'cargada_press' },
  push_jerk:    { nombre: 'Envión de empuje (push jerk)', ej: 'push_press' },
  push_press:   { nombre: 'Push press', ej: 'push_press' },
  thruster:     { nombre: 'Thrusters', ej: 'thruster' },
  arranque:     { nombre: 'Arranque de potencia', ej: 'arranque' },
  arranque_sent:{ nombre: 'Arranque con sentadilla', ej: 'arranque' },
  ohs:          { nombre: 'Sentadilla overhead', ej: 'ohs' },
  sent_frontal: { nombre: 'Sentadilla frontal', ej: 'sent_frontal' },
  sent_tras:    { nombre: 'Sentadilla trasera', ej: 'sent' },
  press:        { nombre: 'Press militar estricto', ej: 'press_pie' },
  banca:        { nombre: 'Press de banca', ej: 'press_banca' },
  pistol:       { nombre: 'Sentadillas a una pierna (pistol)', ej: 'pistol' },
  fondos:       { nombre: 'Fondos', ej: 'dips' },
  muscle_up:    { nombre: 'Muscle-ups', ej: 'muscle_up' },
  k2e:          { nombre: 'Rodillas a los codos', ej: 'elev_piernas' },
  t2b:          { nombre: 'Pies a la barra', ej: 'elev_piernas' },
  zancadas:     { nombre: 'Zancadas caminando', ej: 'zancadas_maletas' },
  cuerda:       { nombre: 'Saltos de cuerda', ej: 'cuerda' },
  dobles:       { nombre: 'Saltos dobles de cuerda', ej: 'cuerda' },
  correr:       { nombre: 'Correr', ej: 'correr' },
  correr_atras: { nombre: 'Correr hacia atrás', ej: 'correr' },
  fondos_anilla:{ nombre: 'Fondos en anillas', ej: 'fondos_anillas' },
  swing:        { nombre: 'Swings con pesa rusa', ej: 'swing_disco', falta: 'Sin pesa rusa: swing con un disco de 20 kg (o de 15).' },
  wall_ball:    { nombre: 'Wall balls', ej: 'thruster', falta: 'Sin balón: thrusters con la barra sola o con poco peso.' },
  remo_erg:     { nombre: 'Remo en máquina', ej: 'correr', falta: 'Sin remoergómetro: corre la misma distancia o haz 1 minuto de cuerda por cada 250 m.' },
  cajon:        { nombre: 'Saltos al cajón', ej: 'salto_cajon', falta: 'Sin cajón: al banco si es firme; si no, saltos de sentadilla.' },
  trepa:        { nombre: 'Trepas de cuerda', ej: 'dominadas_toalla', falta: 'Sin cuerda para trepar: 3 dominadas con toalla por cada trepa.' },
  extension:    { nombre: 'Extensiones de espalda', ej: 'buenos_dias', falta: 'Sin banco romano: buenos días con la barra sola.' },
  ghd:          { nombre: 'Abdominales en GHD', ej: 'sit_up', falta: 'Sin GHD: abdominales con disco, o 1 rueda abdominal por cada 2.' },
  sdhp:         { nombre: 'Peso muerto sumo con jalón alto', ej: 'remo_cuello' },
  limpiapara:   { nombre: 'Limpiaparabrisas con barra', ej: 'elev_piernas' },
  kb_press:     { nombre: 'Cargada y press con pesa rusa a una mano', ej: 'cargada_press', falta: 'Sin pesa rusa: cargada y press con la barra liviana.' },
  db_cargada:   { nombre: 'Cargadas con sentadilla con mancuernas', ej: 'cargada', falta: 'Sin mancuernas: cargadas con barra (las maletas pesan demasiado).' },
  step_up:      { nombre: 'Subidas al cajón con mochila', ej: 'zancadas_maletas', falta: 'Sin cajón: subidas al banco con tu chaleco de 10 kg (el RX pide 20 kg; súmale una mochila con un disco si quieres el peso completo).' },
};

const GRUPOS_WOD = [
  { id: 'chicas', nombre: 'Las Chicas', intro: 'Los WOD de referencia que CrossFit empezó a publicar en 2003. Se llaman como las tormentas: el que los inventó decía que te dejan como si te hubiera pasado una encima.' },
  { id: 'heroes', nombre: 'Héroes', intro: 'WOD en honor a militares, policías y bomberos muertos en servicio. Son largos y duros a propósito.' },
  { id: 'clasicos', nombre: 'Otros clásicos', intro: 'Pruebas famosas que no son Chicas ni Héroes.' },
];

/* tipo: tiempo (lo más rápido posible), amrap (rondas en el tiempo dado),
   emom (cada minuto), tabata, intervalos o max (máximo de repeticiones).
   min: duración (amrap, emom) o tiempo límite sugerido (tiempo). */
const WODS = [
  /* ------------------------------ Chicas ------------------------------ */
  { id: 'angie', nombre: 'Angie', grupo: 'chicas', tipo: 'tiempo', min: 30, formato: 'Por tiempo',
    mov: [['100', 'dominadas'], ['100', 'flexiones'], ['100', 'abdominales'], ['100', 'sentadillas']],
    nota: 'Hay que terminar cada ejercicio antes de pasar al siguiente.', escalado: '50 de cada uno.' },
  { id: 'barbara', nombre: 'Barbara', grupo: 'chicas', tipo: 'tiempo', min: 40, formato: '5 rondas por tiempo, 3 minutos de descanso entre rondas',
    mov: [['20', 'dominadas'], ['30', 'flexiones'], ['40', 'abdominales'], ['50', 'sentadillas']],
    escalado: '3 rondas, o la mitad de las repeticiones.' },
  { id: 'chelsea', nombre: 'Chelsea', grupo: 'chicas', tipo: 'emom', min: 30, formato: 'Cada minuto durante 30 minutos',
    mov: [['5', 'dominadas'], ['10', 'flexiones'], ['15', 'sentadillas']],
    nota: 'Si un minuto no te alcanza, el WOD termina ahí: anota cuántos minutos completaste.', escalado: 'EMOM de 20 minutos.' },
  { id: 'cindy', nombre: 'Cindy', grupo: 'chicas', tipo: 'amrap', min: 20, formato: 'Máximo de rondas en 20 minutos',
    mov: [['5', 'dominadas'], ['10', 'flexiones'], ['15', 'sentadillas']],
    nota: 'Se anotan las rondas completas más las repeticiones sueltas.', escalado: 'Dominadas con tu banda (o con salto).' },
  { id: 'diane', nombre: 'Diane', grupo: 'chicas', tipo: 'tiempo', min: 10, formato: '21-15-9 por tiempo',
    mov: [['21-15-9', 'peso_muerto', '100 / 70 kg'], ['21-15-9', 'hspu']],
    escalado: 'Peso muerto con 60-70 % de la carga; flexiones con los pies en el banco en vez de pino.' },
  { id: 'elizabeth', nombre: 'Elizabeth', grupo: 'chicas', tipo: 'tiempo', min: 12, formato: '21-15-9 por tiempo',
    mov: [['21-15-9', 'cargada_sent', '60 / 43 kg'], ['21-15-9', 'fondos_anilla']],
    escalado: 'Cargadas de potencia con 40 kg; fondos en paralelas.' },
  { id: 'fran', nombre: 'Fran', grupo: 'chicas', tipo: 'tiempo', min: 10, formato: '21-15-9 por tiempo',
    mov: [['21-15-9', 'thruster', '43 / 29 kg'], ['21-15-9', 'dominadas']],
    nota: 'El más famoso de todos. Un tiempo bajo 5 minutos es muy bueno; los mejores del mundo lo hacen en menos de 2.', escalado: 'Thrusters con 30 kg; dominadas con banda.' },
  { id: 'grace', nombre: 'Grace', grupo: 'chicas', tipo: 'tiempo', min: 10, formato: '30 repeticiones por tiempo',
    mov: [['30', 'envion', '60 / 43 kg']], escalado: 'Con 40 kg o menos.' },
  { id: 'helen', nombre: 'Helen', grupo: 'chicas', tipo: 'tiempo', min: 15, formato: '3 rondas por tiempo',
    mov: [['400 m', 'correr'], ['21', 'swing', '24 / 16 kg'], ['12', 'dominadas']], escalado: 'Swings más livianos; dominadas con banda.' },
  { id: 'isabel', nombre: 'Isabel', grupo: 'chicas', tipo: 'tiempo', min: 10, formato: '30 repeticiones por tiempo',
    mov: [['30', 'arranque', '60 / 43 kg']], escalado: 'Con 30 kg o con la barra sola.' },
  { id: 'jackie', nombre: 'Jackie', grupo: 'chicas', tipo: 'tiempo', min: 15, formato: 'Por tiempo',
    mov: [['1000 m', 'remo_erg'], ['50', 'thruster', '20 / 15 kg'], ['30', 'dominadas']], escalado: '500 m, 30 thrusters y 20 dominadas.' },
  { id: 'karen', nombre: 'Karen', grupo: 'chicas', tipo: 'tiempo', min: 15, formato: '150 repeticiones por tiempo',
    mov: [['150', 'wall_ball', '9 / 6 kg']], escalado: '100 repeticiones.' },
  { id: 'linda', nombre: 'Linda', grupo: 'chicas', tipo: 'tiempo', min: 35, formato: '10-9-8-7-6-5-4-3-2-1 por tiempo',
    mov: [['10 a 1', 'peso_muerto', '1,5 × tu peso'], ['10 a 1', 'banca', 'tu peso'], ['10 a 1', 'cargada', '0,75 × tu peso']],
    nota: 'También le dicen «las tres barras de la muerte».', escalado: 'Peso muerto con tu peso, banca con la mitad y cargada con la mitad.' },
  { id: 'mary', nombre: 'Mary', grupo: 'chicas', tipo: 'amrap', min: 20, formato: 'Máximo de rondas en 20 minutos',
    mov: [['5', 'hspu'], ['10', 'pistol'], ['15', 'dominadas']], escalado: 'Pistols agarrado de la jaula; flexiones con los pies en el banco.' },
  { id: 'nancy', nombre: 'Nancy', grupo: 'chicas', tipo: 'tiempo', min: 25, formato: '5 rondas por tiempo',
    mov: [['400 m', 'correr'], ['15', 'ohs', '43 / 29 kg']], escalado: 'Overhead con 20-30 kg.' },
  { id: 'annie', nombre: 'Annie', grupo: 'chicas', tipo: 'tiempo', min: 15, formato: '50-40-30-20-10 por tiempo',
    mov: [['50-40-30-20-10', 'dobles'], ['50-40-30-20-10', 'abdominales']], escalado: 'Saltos simples: el triple de repeticiones.' },
  { id: 'eva', nombre: 'Eva', grupo: 'chicas', tipo: 'tiempo', min: 60, formato: '5 rondas por tiempo',
    mov: [['800 m', 'correr'], ['30', 'swing', '32 / 24 kg'], ['30', 'dominadas']], escalado: '3 rondas.' },
  { id: 'kelly', nombre: 'Kelly', grupo: 'chicas', tipo: 'tiempo', min: 40, formato: '5 rondas por tiempo',
    mov: [['400 m', 'correr'], ['30', 'cajon', '60 / 50 cm'], ['30', 'wall_ball', '9 / 6 kg']], escalado: '3 rondas.' },
  { id: 'lynne', nombre: 'Lynne', grupo: 'chicas', tipo: 'max', min: 20, formato: '5 rondas, máximo de repeticiones',
    mov: [['máx.', 'banca', 'tu peso'], ['máx.', 'dominadas']], nota: 'Sin tiempo: se suman todas las repeticiones de las 5 rondas.', escalado: 'Banca con la mitad de tu peso.' },
  { id: 'nicole', nombre: 'Nicole', grupo: 'chicas', tipo: 'amrap', min: 20, formato: 'Máximo de rondas en 20 minutos',
    mov: [['400 m', 'correr'], ['máx.', 'dominadas']], nota: 'Se anotan las dominadas de cada ronda.' },
  { id: 'amanda', nombre: 'Amanda', grupo: 'chicas', tipo: 'tiempo', min: 15, formato: '9-7-5 por tiempo',
    mov: [['9-7-5', 'muscle_up'], ['9-7-5', 'arranque_sent', '61 / 43 kg']], escalado: 'Muscle-up: 2 dominadas y 2 fondos en anillas por cada uno (o muscle-up con banda); arranques con 30 kg.' },
  { id: 'gwen', nombre: 'Gwen', grupo: 'chicas', tipo: 'max', min: 20, formato: '15-12-9 sin soltar la barra, descansando lo que necesites entre series',
    mov: [['15-12-9', 'envion', 'el mismo peso, lo más pesado posible']], nota: 'Se anota el peso. Si sueltas la barra en una serie, esa serie no vale.' },
  { id: 'candy', nombre: 'Candy', grupo: 'chicas', tipo: 'tiempo', min: 40, formato: '5 rondas por tiempo',
    mov: [['20', 'dominadas'], ['40', 'flexiones'], ['60', 'sentadillas']], escalado: '3 rondas.' },
  { id: 'maggie', nombre: 'Maggie', grupo: 'chicas', tipo: 'tiempo', min: 45, formato: '5 rondas por tiempo',
    mov: [['20', 'hspu'], ['40', 'dominadas'], ['60', 'pistol']], escalado: 'La mitad de las repeticiones.' },

  /* ------------------------------ Héroes ------------------------------ */
  { id: 'murph', nombre: 'Murph', grupo: 'heroes', tipo: 'tiempo', min: 60, formato: 'Por tiempo, con chaleco de 9 kg (tu chaleco de 10 kg sirve: es RX)',
    mov: [['1,6 km', 'correr'], ['100', 'dominadas'], ['200', 'flexiones'], ['300', 'sentadillas'], ['1,6 km', 'correr']],
    nota: 'En honor al teniente Michael Murphy, Navy SEAL, muerto en Afganistán en 2005. Se puede repartir: 20 rondas de 5 dominadas, 10 flexiones y 15 sentadillas.',
    escalado: 'Primero sin chaleco; después, el completo con chaleco. O la mitad («medio Murph»).' },
  { id: 'dt', nombre: 'DT', grupo: 'heroes', tipo: 'tiempo', min: 20, formato: '5 rondas por tiempo',
    mov: [['12', 'peso_muerto', '70 / 47 kg'], ['9', 'colgante', '70 / 47 kg'], ['6', 'push_jerk', '70 / 47 kg']],
    nota: 'En honor al sargento Timothy P. Davis, de la Fuerza Aérea de EE. UU., muerto en 2009. Todo con la misma barra.', escalado: 'Con 40-50 kg.' },
  { id: 'jt', nombre: 'JT', grupo: 'heroes', tipo: 'tiempo', min: 20, formato: '21-15-9 por tiempo',
    mov: [['21-15-9', 'hspu'], ['21-15-9', 'fondos_anilla'], ['21-15-9', 'flexiones']],
    nota: 'En honor a Jeff Taylor, suboficial de la Marina de EE. UU., muerto en 2005.', escalado: 'Flexiones con los pies en el banco en vez de pino.' },
  { id: 'michael', nombre: 'Michael', grupo: 'heroes', tipo: 'tiempo', min: 40, formato: '3 rondas por tiempo',
    mov: [['800 m', 'correr'], ['50', 'extension'], ['50', 'abdominales']],
    nota: 'En honor al teniente Michael McGreevy, Navy SEAL, muerto en Afganistán en 2005.' },
  { id: 'randy', nombre: 'Randy', grupo: 'heroes', tipo: 'tiempo', min: 15, formato: '75 repeticiones por tiempo',
    mov: [['75', 'arranque', '34 / 25 kg']], nota: 'En honor a Randy Simmons, policía de la unidad SWAT de Los Ángeles, muerto en 2008.' },
  { id: 'nate', nombre: 'Nate', grupo: 'heroes', tipo: 'amrap', min: 20, formato: 'Máximo de rondas en 20 minutos',
    mov: [['2', 'muscle_up'], ['4', 'hspu'], ['8', 'swing', '32 / 24 kg']],
    nota: 'En honor a Nate Hardy, suboficial jefe y Navy SEAL, muerto en Irak en 2008.' },
  { id: 'josh', nombre: 'Josh', grupo: 'heroes', tipo: 'tiempo', min: 25, formato: 'Por tiempo',
    mov: [['21 · 15 · 9', 'ohs', '43 / 29 kg'], ['42 · 30 · 18', 'dominadas']],
    nota: 'En honor al sargento Joshua Whitaker, del Ejército de EE. UU., muerto en Afganistán en 2007. Se intercalan: 21 overhead, 42 dominadas, 15, 30, 9, 18.' },
  { id: 'badger', nombre: 'Badger', grupo: 'heroes', tipo: 'tiempo', min: 45, formato: '3 rondas por tiempo',
    mov: [['30', 'cargada_sent', '43 / 29 kg'], ['30', 'dominadas'], ['800 m', 'correr']],
    nota: 'En honor a Mark Carter, suboficial jefe y Navy SEAL, muerto en Irak en 2007.' },
  { id: 'daniel', nombre: 'Daniel', grupo: 'heroes', tipo: 'tiempo', min: 35, formato: 'Por tiempo',
    mov: [['50', 'dominadas'], ['400 m', 'correr'], ['21', 'thruster', '43 / 29 kg'], ['800 m', 'correr'], ['21', 'thruster', '43 / 29 kg'], ['400 m', 'correr'], ['50', 'dominadas']],
    nota: 'En honor al sargento primero Daniel Crabtree, del Ejército de EE. UU., muerto en Irak en 2006.' },
  { id: 'griff', nombre: 'Griff', grupo: 'heroes', tipo: 'tiempo', min: 25, formato: 'Por tiempo',
    mov: [['800 m', 'correr'], ['400 m', 'correr_atras'], ['800 m', 'correr'], ['400 m', 'correr_atras']],
    nota: 'En honor al sargento Travis Griffin, de la Fuerza Aérea de EE. UU., muerto en Irak en 2008.' },
  { id: 'ryan', nombre: 'Ryan', grupo: 'heroes', tipo: 'tiempo', min: 30, formato: '5 rondas por tiempo',
    mov: [['7', 'muscle_up'], ['21', 'burpees']], nota: 'En honor a Ryan Hummert, bombero de Maplewood (Misuri), muerto en 2008.' },
  { id: 'tommyv', nombre: 'Tommy V', grupo: 'heroes', tipo: 'tiempo', min: 30, formato: 'Por tiempo',
    mov: [['21 · 15 · 9', 'thruster', '52 / 34 kg'], ['12 · 9 · 6', 'trepa']],
    nota: 'En honor a Thomas Valentine, suboficial mayor y Navy SEAL, muerto en 2008. Se intercalan: 21 thrusters, 12 trepas, 15, 9, 9, 6.' },
  { id: 'jason', nombre: 'Jason', grupo: 'heroes', tipo: 'tiempo', min: 30, formato: 'Por tiempo',
    mov: [['100 · 75 · 50 · 25', 'sentadillas'], ['5 · 10 · 15 · 20', 'muscle_up']],
    nota: 'En honor a Jason Lewis, Navy SEAL, muerto en Irak en 2007. Se intercalan: 100 sentadillas, 5 muscle-ups, 75, 10…' },
  { id: 'holleyman', nombre: 'Holleyman', grupo: 'heroes', tipo: 'tiempo', min: 40, formato: '30 rondas por tiempo',
    mov: [['5', 'wall_ball', '9 / 6 kg'], ['3', 'hspu'], ['1', 'cargada', '102 / 70 kg']],
    nota: 'En honor al sargento Aaron Holleyman, de las Fuerzas Especiales de EE. UU., muerto en Irak en 2004.' },
  { id: 'theseven', nombre: 'The Seven', grupo: 'heroes', tipo: 'tiempo', min: 45, formato: '7 rondas por tiempo',
    mov: [['7', 'hspu'], ['7', 'thruster', '61 / 43 kg'], ['7', 'k2e'], ['7', 'peso_muerto', '111 / 75 kg'], ['7', 'burpees'], ['7', 'swing', '32 / 24 kg'], ['7', 'dominadas']],
    nota: 'En honor a siete agentes de la CIA muertos en un atentado en Afganistán en 2009.' },
  { id: 'lumberjack', nombre: 'Lumberjack 20', grupo: 'heroes', tipo: 'tiempo', min: 50, formato: 'Por tiempo; 400 m de carrera después de cada ejercicio',
    mov: [['20', 'peso_muerto', '125 / 84 kg'], ['20', 'swing', '32 / 24 kg'], ['20', 'ohs', '52 / 34 kg'], ['20', 'burpees'], ['20', 'dom_pecho'], ['20', 'cajon', '60 / 50 cm'], ['20', 'db_cargada', '2 × 20 / 2 × 15 kg'], ['7 × 400 m', 'correr']],
    nota: 'En honor a las víctimas del tiroteo de Fort Hood (Texas) en 2009.' },
  { id: 'kalsu', nombre: 'Kalsu', grupo: 'heroes', tipo: 'tiempo', min: 30, formato: 'Por tiempo: al empezar cada minuto, 5 burpees primero',
    mov: [['100', 'thruster', '61 / 43 kg'], ['5 por minuto', 'burpees']],
    nota: 'En honor a Bob Kalsu, jugador de fútbol americano de la NFL que murió en Vietnam en 1970. Uno de los más brutales.' , reloj: { modo: 'tabata', prep: 10, trabajo: 60, descanso: 0, rondas: 30 } },
  { id: 'bull', nombre: 'Bull', grupo: 'heroes', tipo: 'tiempo', min: 60, formato: '2 rondas por tiempo',
    mov: [['200', 'dobles'], ['50', 'ohs', '61 / 43 kg'], ['50', 'dominadas'], ['1,6 km', 'correr']],
    nota: 'En honor al capitán Brandon «Bull» Barrett, de los Marines de EE. UU., muerto en Afganistán en 2010.' },
  { id: 'chad', nombre: 'Chad', grupo: 'heroes', tipo: 'tiempo', min: 60, formato: '1000 repeticiones por tiempo',
    mov: [['1000', 'step_up', 'mochila de 20 / 14 kg']],
    nota: 'En honor a Chad Wilkinson, Navy SEAL, para hablar del suicidio de veteranos. Se suele hacer en grupo.' },

  /* ------------------------------ Clásicos ------------------------------ */
  { id: 'fgb', nombre: 'Fight Gone Bad', grupo: 'clasicos', tipo: 'intervalos', min: 17, formato: '3 rondas: 1 minuto en cada estación y 1 minuto de descanso',
    mov: [['1 min', 'wall_ball', '9 / 6 kg'], ['1 min', 'sdhp', '34 / 25 kg'], ['1 min', 'cajon', '50 cm'], ['1 min', 'push_press', '34 / 25 kg'], ['1 min', 'remo_erg', 'calorías']],
    nota: 'Se suman todas las repeticiones. Lo diseñaron pensando en un combate de MMA.', reloj: { modo: 'tabata', prep: 10, trabajo: 60, descanso: 0, rondas: 18 } },
  { id: 'filthy50', nombre: 'Filthy Fifty', grupo: 'clasicos', tipo: 'tiempo', min: 40, formato: '50 de cada uno, en orden, por tiempo',
    mov: [['50', 'cajon', '60 cm'], ['50', 'dom_salto'], ['50', 'swing', '16 kg'], ['50', 'zancadas'], ['50', 'k2e'], ['50', 'push_press', '20 kg'], ['50', 'extension'], ['50', 'wall_ball', '9 kg'], ['50', 'burpees'], ['50', 'dobles']] },
  { id: 'tse', nombre: 'Tabata Something Else', grupo: 'clasicos', tipo: 'tabata', min: 16, formato: '4 tábatas seguidos (20 s de trabajo, 10 de descanso, 8 rondas cada uno)',
    mov: [['8 × 20 s', 'dominadas'], ['8 × 20 s', 'flexiones'], ['8 × 20 s', 'abdominales'], ['8 × 20 s', 'sentadillas']],
    nota: 'Se suman todas las repeticiones.', reloj: { modo: 'tabata', prep: 10, trabajo: 20, descanso: 10, rondas: 32 } },
  { id: 'chief', nombre: 'The Chief', grupo: 'clasicos', tipo: 'intervalos', min: 19, formato: '5 bloques de 3 minutos (máximo de rondas) con 1 minuto de descanso',
    mov: [['3', 'cargada', '61 / 43 kg'], ['6', 'flexiones'], ['9', 'sentadillas']],
    nota: 'Se suman las rondas de los 5 bloques.', reloj: { modo: 'tabata', prep: 10, trabajo: 180, descanso: 60, rondas: 5 } },
  { id: 'deathpull', nombre: 'Muerte por dominadas', grupo: 'clasicos', tipo: 'emom', min: 20, formato: 'Cada minuto: 1 dominada el primero, 2 el segundo, 3 el tercero… hasta que no alcances',
    mov: [['1, 2, 3…', 'dominadas']], nota: 'Se anota el último minuto completo.', reloj: { modo: 'tabata', prep: 10, trabajo: 60, descanso: 0, rondas: 30 } },
  { id: 'baseline', nombre: 'Baseline', grupo: 'clasicos', tipo: 'tiempo', min: 10, formato: 'Por tiempo',
    mov: [['500 m', 'remo_erg'], ['40', 'sentadillas'], ['30', 'abdominales'], ['20', 'flexiones'], ['10', 'dominadas']],
    nota: 'La prueba de entrada que se usa en muchos boxes para medir el punto de partida.' },
  { id: 'trescientos', nombre: '300 (Espartanos)', grupo: 'clasicos', tipo: 'tiempo', min: 30, formato: 'Por tiempo',
    mov: [['25', 'dominadas'], ['50', 'peso_muerto', '61 kg'], ['50', 'flexiones'], ['50', 'cajon', '60 cm'], ['50', 'limpiapara', '61 kg'], ['50', 'kb_press', '16 kg'], ['25', 'dominadas']],
    nota: 'El entrenamiento que se hizo famoso con la película 300.' },
  { id: 'total', nombre: 'CrossFit Total', grupo: 'clasicos', tipo: 'max', min: 45, formato: 'Una repetición máxima en cada uno; 3 intentos por ejercicio',
    mov: [['1 RM', 'sent_tras'], ['1 RM', 'press'], ['1 RM', 'peso_muerto']],
    nota: 'Se suman los tres kilos. Kubik lo aprobaría: pocos levantamientos y pesados.' },
];

const WOD = Object.fromEntries(WODS.map(w => [w.id, w]));
